name: John

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: "Cache Data"
        with:
          path: |
            rockyou.txt
            john-1.8.0.9-jumbo-macosx_sse4
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}

      - name: Install Dependencies
        run: |
          if test -f "rockyou.txt"; then
              echo "FILE exists."
          else
              echo "NOT exists. DOWNLOADING..."
              curl https://download.openwall.net/pub/projects/john/contrib/macosx/john-1.8.0.9-jumbo-macosx_sse4.zip -O
              curl https://download.weakpass.com/wordlists/90/rockyou.txt.gz -O
              gunzip rockyou.txt.gz
              unzip john-1.8.0.9-jumbo-macosx_sse4.zip
          fi
      
      - name: Checking 
        run: |
          ls -la
          ls -la john-1.8.0.9-jumbo-macosx_sse4
          ls -la john-1.8.0.9-jumbo-macosx_sse4/run
          john-1.8.0.9-jumbo-macosx_sse4/run/john
          john-1.8.0.9-jumbo-macosx_sse4/run/john --list=formats | grep phpass

      - name: Cracking
        run: |
          john-1.8.0.9-jumbo-macosx_sse4/run/john --format=gpg -w=rockyou.txt hash

      - name: Show
        run: |
          john-1.8.0.9-jumbo-macosx_sse4/run/john --show hash > result.txt
          echo "RESULT=$(cat result.txt)" >> $GITHUB_OUTPUT
          cat result.txt
        id: show_result
      
      - name: Send mail
        run: |
          chmod +x mail.sh
          ./mail.sh ${{ secrets.SMTP_CLIENT }} ${{ steps.show_result.outputs.RESULT }}

